{% set version = "4.7.2" %}

package:
  name: pymongo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymongo/pymongo-{{ version }}.tar.gz
  sha256: 9024e1661c6e40acf468177bf90ce924d1bc681d2b244adda3ed7b2f4c4d17d7

build:
  number: 0
  script: python -m pip install . -vv
  # Three tests seem to fail on PPC64LE and PyPy
  # test_monitoring test_gridfs_spec test_legacy_api
  script_env:
    - python_impl
    - target_platform

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - dnspython >=1.16.0,<3.0.0

test:
  source_files:
    - .
  files:
    - run_the_tests.sh
  imports:
    - bson
    - gridfs
    - pymongo
  requires:
    - mongodb     # [not win]
    - setuptools  # [not win]
    - pytest
    - mockupdb
    - pip
  commands:
    - bash run_the_tests.sh  # [unix and not (ppc64le or python_impl=='pypy')]
    - pip check

about:
  home: https://github.com/mongodb/mongo-python-driver
  license: Apache-2.0
  license_file: LICENSE
  summary: Python driver for MongoDB http://www.mongodb.org
  dev_url: https://github.com/mongodb/mongo-python-driver

extra:
  recipe-maintainers:
    - xylar
    - ShaneHarvey
    - blink1073
    - licode
    - tacaswell
    - CJ-Wright
    - jan-janssen
