{% set name = "pymongo" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  fn: {{ name }}-{{ version }}.tar.gz
  sha256: d359349c6c9ff9f482805f89e66e476846317dc7b1eea979d7da9c0857ee2721

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - ipadress  # [py2k]
    - wincertstore >=0.2  # [win32]
    - pykerberos  # [not win32]

test:
  imports:
    - bson
    - gridfs
    - pymongo

about:
  home: https://github.com/mongodb/mongo-python-driver
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'Python driver for MongoDB'
  dev_url: https://github.com/mongodb/mongo-python-driver
  doc_url: http://api.mongodb.com/python/3.4.0/

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - jakirkham
    - tacaswell
