{% set version = "3.11.0" %}

package:
  name: pymongo
  version: {{ version }}

source:
  url: https://github.com/mongodb/mongo-python-driver/archive/{{ version }}.tar.gz
  sha256: e45b318c56f5f385635df06685104ae22f3c9977addaa2dad0d1dc94f31f20c7
  patches:
    # https://github.com/mongodb/mongo-python-driver/pull/485/
    - python-3.9.diff

build:
  number: 5
  script: python -m pip install . -vv
  # Three tests seem to fail on PPC64LE and PyPy
  # test_monitoring test_gridfs_spec test_legacy_api
  script_env:
    - python_impl
    - target_platform

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  source_files:
    - .
  files:
    - run_the_tests.sh
  imports:
    - bson
    - gridfs
    - pymongo
  requires:       # [not win]
    - mongodb     # [not win]
    - setuptools  # [not win]
  commands:                  # [unix and not (ppc64le and python_impl=='pypy')]
    - bash run_the_tests.sh  # [unix and not (ppc64le and python_impl=='pypy')]

about:
  home: https://github.com/mongodb/mongo-python-driver
  license: Apache-2.0
  license_file: LICENSE
  summary: Python driver for MongoDB http://www.mongodb.org

extra:
  recipe-maintainers:
    - licode
    - tacaswell
    - CJ-Wright
