{% set name = "pymongo" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  fn: {{ name }}-{{ version }}.tar.gz
  sha256: c6de26d1e171cdc449745b82f1addbc873d105b8e7335097da991c0fc664a4a8

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  script_env:  # [osx]
    - TRAVIS   # [osx]

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  source_files:
    - .
  imports:
    - bson
    - gridfs
    - pymongo
  requires:  # [not win]
    - mongodb  # [not win]
    - setuptools  # [not win]

about:
  home: https://github.com/mongodb/mongo-python-driver
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: Python driver for MongoDB http://www.mongodb.org
  dev_url: https://github.com/mongodb/mongo-python-driver
  doc_url: http://api.mongodb.com/python/{{ version }}/

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - jakirkham
    - tacaswell
    - CJ-Wright
