{% set version = "3.7.0" %}

package:
  name: pymongo
  version: {{ version }}

source:
  url: https://github.com/mongodb/mongo-python-driver/archive/{{ version }}.tar.gz
  fn: pymongo-{{ version }}.tar.gz
  sha256: c4c92cc09a8f97f743c64933f3447b015e211a344c952b1af280afa6f44308e1

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  script_env:  # [osx]
    - TRAVIS   # [osx]

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  source_files:
    - .
  imports:
    - bson
    - gridfs
    - pymongo
  requires:  # [not win]
    - mongodb  # [not win]
    - setuptools  # [not win]

about:
  home: https://github.com/mongodb/mongo-python-driver
  license: Apache 2.0
  license_file: LICENSE
  summary: Python driver for MongoDB http://www.mongodb.org

extra:
  recipe-maintainers:
    - licode
    - jakirkham
    - tacaswell
    - CJ-Wright
