# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "R0RwtQLbik0iI2oF0UvK+DsnVIFd9+0P1a0JHAnat1lcrHltn9DbJaUWq3y4G3apgteUY7JfBj7iNiNwzm3uCmoBaOEaNtA3jGxrhVmy0xFxjDthmMRm5hDtPJd0hTK2XPCAVEqoFFWGRYQ60cYMko0j8ICl2o0/kYs7vuBAkuKv0rE25pW83Mq9g4iJFy3WOsGRiYZTG1T2DLJp7wNR2BH4YOkdaE6ygEqrb+M8gV5rgdvz+8rinSdZyhfNnazl5jrKRxXt3aU59RIGV+M3wcImHB2/muJRlbOROImtwzAB7UFkheYOSff9N59MhVp0IUivNwPjZa/f0qL6bZgN6lvdFjuUyYlRnhZsEib6WMHAU7IHvKA2sZsAWdyVeXfRKL910CByxsJ5pu4st15C3IOt6foGEhAaEkHtLgvy+VxT7nnmc6kCZry/RqnASgCfkuSb7MokpGt/6ym3lDwcFeQrS0uRvjsgJFi5nnINihiUpP3L90ySKCbPBqpxm4dqBd+cuZN/iaokf6g4EqIIUvEPbOv5rSjuU2Qauf60RwrSkL6xzVj15pQYpu9vAtMIELVyRY5Y+WxEJli0KKBsOZN5uS0UNT+3OgBtgI8B9cB75lNXn0ROFdiJYifFq91UdeVGhWQt2KqTum/W3+bxccQSGlffQm9n/U3M/xSCnZM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
